#!/bin/sh
OLDPATH=$PATH
WHEREAMI=`pwd`
export PATH=$WHEREAMI/node/bin:"$PATH"
NODEINST=`which node`

NODEARCH=`uname -m`
OLDPATH=$PATH
WHEREAMI=`pwd`

DARWIN_FLAG=`uname -a | grep "Darwin"`

if [ ! -d "$WHEREAMI/nodejs-runtime" ]; then
  git clone https://github.com/internetofcoins/nodejs-runtime
fi

if [ ! -d "$WHEREAMI/nodejs-runtime/darwin-x64" ]; then
  cd nodejs-runtime
  git pull origin master
  cd ..
fi

if [ ! -L "$WHEREAMI/node" ]; then
  ln -s "./nodejs-runtime/$NODEARCH" "$WHEREAMI/node"
fi

if [ "$DARWIN_FLAG" != "" ]; then
 # fix node for eat Apple
 rm ./node
 ln -s "./nodejs-runtime/darwin-x64" "$WHEREAMI/node"
fi

echo
echo "Starting transports tus server..."
echo " [i] using node executable $NODEINST"
node exe/server.js
echo
echo

PATH=$OLDPATH
